services:
  shippingd:
    container_name: shippingd
    build: .
    restart: always
    volumes:
      - "./:/app"
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/shared/node_modules
    env_file:
      - .env
    ports:
      - 5173:5173
      - '${API_PORT}:${API_PORT}'
      - "8001:8001"
    networks:
      - shippingnet
  shippingdb:
    container_name: shippingdb
    image: 'mysql'
    restart: always
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_TCP_PORT: '${MYSQL_PORT}'
      MYSQL_ALLOW_EMPY_PASSWORD: '1'
    healthcheck:
      test: [ 'CMD', 'mysqladmin', '-u${DB_USERNAME}', '-p${DB_PASSWORD}', 'ping' ]
      retries: 3
      timeout: 5s
    networks:
      - shippingnet

  shippingr:
    container_name: shippingr
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "${REDIS_PORT}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - "./docker-volume/redis/data:/data"
      - "./docker-volume/redis/conf:/usr/local/etc/redis/redis.conf"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    networks:
      - shippingnet

networks:
  shippingnet:
    name: shippingnet
